stages:
  - build
  - test

default:
  stage: build
  image: ubuntu:20.04
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install libpq-dev
    - apt -y install net-tools python3.8 python3-pip python3-psycopg2
    - apt -y upgrade
    - pip3 install -r req.txt


migrations:
  stage: build
  script:
    echo "python manage.py makemigrations"
    echo "python manage.py migrate"
    echo "python manage.py initadmin"
    echo "python manage.py runserver 0.0.0.0:7000"
    - chmod +x ./entrypoint.sh


django-tests:
  stage: test
  script:
    echo "python manage.py test"
    - python manage.py test


pytest-tests:
  stage: test
  script:
    echo "pytest -rA tests\test_tasks.py"
    - pytest -rA tests\test_tasks.py
