version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
    - "7000:7000"
    
  celery_worker:
    restart: always
    build:
      context: ./
    command: celery -A notifications worker -l INFO
    depends_on:
      - app
      
  celery_beat:
    restart: always
    build:
      context: ./
    command: celery -A notifications beat -l INFO
    depends_on:
      - app
      - celery_worker
