version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
    restart: always
    ports:
    - "7000:7000"
    
  celery_worker:
    restart: always
    build:
      context: ./
    command: celery -A app worker -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - app
      
  celery_beat:
    restart: always
    build:
      context: ./
    command: celery -A app beat -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - app
      - celery_worker
